default: &default
  adapter: mysql2
  encoding: utf8
  username: root
  # password:
  host: localhost
  # port: 5432
  # pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # schema_search_path: myapp,sharedapp,public
  # min_messages: notice

development:
  <<: *default
  database: sagan_development

test:
  <<: *default
  database: sagan_test

production:
  <<: *default
  url: ENV["DATABASE_URL"]
